#CADA ESPAÇO TEM UM INDICE, LETRAS, NUMEROS, ESPAÇOS, E ETC - CADEIA DE CARACTERES
#FATIAR
#FRASE= CURSO EM VIDEO
#FRASE[9] > LE SO ATÉ 9 CARACTERES -
# EX:FRASE[9:13] > NESSE EXEMPLO ELE VAI FATIAR DO CARACTERE 9 AO 12 - O ULTIMO VALOR NÃO ENTRA NA CONTAGEM
#FRASE[9:21] >
#FRASE[9:21:2] NESSE ELE VAI DO 9 AO 20 PULANDO DE DOIS EM DOIS
#FRASE[:5] > OMITO O INICIO = FRASE [0:5]
#FRASE[15:] > N SABENDO O FINAL Q EU QUERO DO 15 AO FINAL
#FRASE[9::3] > VAI COMEÇAR NO 9 E VAI ATE O FINAL PULANDO DE 3 EM 3
#ANALISAR UMA STRING > QUAL O TAMANHO, QUAL A PALAVRA INTEIRA, E ETC ETC
#EX: LEN(FRASE) = 21
#FRASE.COUNT('o') > VAI ME CONTAR QUANTAS VEZES EXISTE A LETRA O NA FRASE
#FRASE.COUNT('O',0,13) > QUANTOS O'S TEM COMEÇANDO DO 0 E INDO ATÉ O 13
#FRASE.FIND('deo') > QUANTAS VEZES ENCONTROU deo na string > MOSTRANDO TBM ONDE É QUE ISSO COMEÇA
#FRASE.FIND('android') > ELE ME RETORNA O VALOR -1 > SIGNIFICA QUE NÃO TEM ESSE TREM NA STRING SELECIONADA
#'Curso' in frase > EXISTE A PALAVRA CURSO EM FRASE > RETORNA TRUE OU FALSE
#TRANSFORMAÇÃO
#FRASE.REPLAC('PYTHON','ANDROID') > ONDE TIVER PYTHON ELE VAI SUBSTITUIR POR ANDROID
#FRASE.UPPER() > DEIXAR TUDO EM MAIUSCULA
#FRASE.LOWER() > DEIXA TUDO MINUSCULA
#FRASE.CAPITALIZE() > A PRIMEIRA LETRA FICA MAIUSCULA E O RESTO FICA MINUSCULA
#FRASE.TITLE() > DEIXA TODAS AS PALAVRAS DEPOIS DO ESPAÇO EM MAIUSCULA
#FRASE.STRIP() > VAI REMOVER OS ESPAÇOS QUE FOREM INUTEIS
#FRASE.rtrip() > O LADO DIREITO DA STRING VAZIO É REMOVIDO
#FRASE.ltrip() < TIRA DA ESQUERDA
#DIVISÃO
#FRASE.SPLIT() > A CADA ESPAÇO ELE SEPARA A STRING, E O QUE FICA DIVIDIDO SE TORNA 1,2,3 (DA PRA ENCAIXAR AI DENTRO De um [] PRA TIRAR UMA PALAVRA ESPECIFICA
#'-'.JOIN(FRASE) > VAI JUNTAR TODOS OS ELEMENTOS DA FRASE SEPARADOS PELO - OU QUALQUER OUTRA COISA
#TESTES
frase= 'Curso em Video Python'
print(frase[:13:2])
